title:              Happy Memories
email:              akimabit@gmail.com
description:        Happy Memories
author:             akimabit
baseurl:            ""
url:                "https://akimabit.github.io"

# Social Profiles
twitter_username:   akimabit
github_username:    akimabit
facebook_username:  akimabit
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
